name: Deploy Node App

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t adeelmalik0014/node-backend .

      - name: Publish Image to Docker Hub
        run: docker push adeelmalik0014/node-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from the docker hub
        run: docker pull adeelmalik0014/node-backend:latest

      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' adeelmalik0014/node-backend
